require('opt')
require('settings')
require('binds')

require('plugins/startify')
require('plugins/telescope')
require('plugins/colorizer')
require('plugins/treesitter')
require('plugins/compe')
require('plugins/kind')
require('plugins/saga')
require('plugins/autopairs')
require('plugins/formatter')
require('plugins/rnvimr')
require('plugins/term')
require('plugins/rooter')
require('plugins/neoscroll')
-- require('plugins/trouble')
-- require('plugins/bufferline')
-- require('plugins/emmet-compe')

require('statusline/init_1')

require('lsp/config')
require('lsp/efm')
require('lsp/tsserver')
require('lsp/html')
require('lsp/css')
require('lsp/lua')
require('lsp/bash')
require('lsp/css')
require('lsp/efm')
require('lsp/html')
require('lsp/json')
require('lsp/lua')
require('lsp/zeta-note')
-- require('lsp/vim')
-- require('lsp/graphql')

require('keymappings')
