require('opt')
require('settings')
require('keymappings')
require('binds')

require('plugins/startify')
require('plugins/telescope')
require('plugins/colorizer')
require('plugins/treesitter')
require('plugins/compe')
require('plugins/kind')
require('plugins/saga')
require('plugins/autopairs')
require('plugins/emmet-compe')
require('plugins/formatter')
require('plugins/rnvimr')
-- require('plugins/trouble')
require('plugins/bufferline')
require('plugins/rooter')
require('plugins/neoscroll')


require('statusline/init')
-- require('lsp/install')
-- require('lsp/config')
-- require('lsp/efm')
-- require('lsp/tsserver')
-- require('lsp/graphql')
-- require('lsp/html')
-- require('lsp/css')
-- require('lsp/lua')

